spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/acts_log
    username: root
    password: 55555
  flyway:
    schemas:
      - public
      - acts_log
  jpa:
    show-sql: true
server:
  port: 8081
logging:
  level:
    sql: info